GO :=echo
GOPATH :=/fixture
GOOS :=linux
GOARCH :=amd64
GOHOSTOS :=linux
GOHOSTARCH :=amd64
GOEXE :=
GOFLAGS :=
GO_REQUIRED_MIN_VERSION :=
GO_PACKAGE :=example.com/component
GO_BUILD_PACKAGES :=./cmd/server ./cmd/helper
GO_BUILD_FLAGS :=-tags=production -trimpath
CRYPTO_CGO_ENABLED :=0
CRYPTO_SCANNER :=./scanner.sh
CRYPTO_INVENTORY_FILE :=./report/source.json

include ../../targets/golang/crypto-inventory.mk
